### ISSUE TITLE
Add brand colors

### ISSUE THREAD

**Issue by yakushabb** [pardus/pardus-pen#12]
> Brand color
> 
> Applications should set a [brand color](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-branding) in both light and dark variants like so:
> 
>```
><branding>
> <color type="primary" scheme_preference="light">#ff00ff</color>
> <color type="primary" scheme_preference="dark">#993d3d</color>
></branding>
>```
> 
> This is used by Flathub and native app store clients on banners, app pages, etc.
> 
> Brand color and app banners can be previewd at https://docs.flathub.org/banner-preview/

https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#brand-color

**Comment by sulincix** [comment]
https://github.com/pardus/pardus-pen/commit/d5b8da8545f8b62e17bcf6bf6030e3d86ea69496

Thx for contribution.
