### ISSUE TITLE
Kalem / Silgi boyutu sorunu

### ISSUE THREAD

**Issue by asandikci** [pardus/pardus-pen#16]
Silgi seçiliyken eğer çizgi türü (kesikli/düz) değiştirilirse otomatik olarak kalem seçiliyor [ki gayet mantıklı bence]. Ancak kalem boyutu silginin boyutuna eşit olmuş oluyor bu durumda. Bar da 35e kadar gitmek yerine 150ye kadar gidebiliyor.

Test etmek için
  - Silgi boyutunu 150 yapın
  - Çizgi türünü değiştirmek için soldaki menüye tıklayın (otomatik olarak kalem seçilir)
  - Şimdi ayarlardan kalem boyutunu değiştirmeye çalışın (barın 150ye kadar gittiğini göreceksiniz

**Comment by sulincix** [comment]
https://github.com/pardus/pardus-pen/commit/0d9ad6f029804b9f457178ada165b1f3b17c178f

çözüldü
