### ISSUE TITLE
Kalem/Silgi Boyutu için öntanımlı değerler

### ISSUE THREAD

**Issue by asandikci** [pardus/pardus-pen#18]
Kullanım kolaylığı adına Kalem/Silgi boyutu altında öntanımlı boyutların olmasının güzel olabileceğini düşünüyorum. örneğin kalem için 5-10-15-25, silgi için 30-60-100-150 vb. Seçilen boyuta ile bar da senkron olmalı

(bu özelliğin "fatih kalem" uygulamasından geçişi kolaylaştıracağı kanısındayım)

**Comment by asandikci** [comment]
not: bar'ın üstüne tıklayınca onar onar ilerliyormuş zaten. Bu durumda belki öntanımlı değerlere çok da gerek olmayabilir. Kararınıza göre bu issue'yi kapatabilirsiniz

**Comment by sulincix** [comment]
Bilerek o şekilde yapıldı. Ayrıca sürgülü olup önizlemeli olması daha işlevler
