### ISSUE TITLE
Typos/grammar/white spaces in pardus-pen.pot

### ISSUE THREAD

**Issue by hugok79** [pardus/pardus-pen#8]
**1** - The `pardus-pen.pot` file contains some grammar issues
For example: "Are you want to clear screen?" and "Are you want to quit Pardus pen?" Shouldn't be: Do you... instead of Are you...

**2** - White spaces in " Size: " and " Color:" are on purpose?

https://github.com/pardus/pardus-pen/blob/31a56bdf5fc4ae545f8adbf92478a5b1e789faaf/po/pardus-pen.pot#L45

https://github.com/pardus/pardus-pen/blob/31a56bdf5fc4ae545f8adbf92478a5b1e789faaf/po/pardus-pen.pot#L49

**Comment by hugok79** [comment]
Question number **1** has been resolved, but what about question number **2**?

**Comment by sulincix** [comment]
https://github.com/pardus/pardus-pen/commit/23615ebf180cf1c37c839474f51c2acdcec62412

fixed

**Comment by hugok79** [comment]
Thank you!
